#!/bin/bash

. common.inc.sh

check_pkgs make unrar-free autoconf automake libtool gcc g++ gperf flex bison texinfo gawk libncurses5-dev \
  libexpat1-dev python-dev python python-serial sed git unzip bash help2man wget bzip2 libtool-bin

git clone --recursive https://github.com/pfalcon/esp-open-sdk.git

cd esp-open-sdk

make STANDALONE=y
make

tar cvzf ../esp-open-sdk-$(git log -1 --format=%ct).tgz -C .. esp-open-sdk/xtensa-lx106-elf

echo "SDK installed. Append \"$(pwd)/xtensa-lx106-elf/bin\" to the \$PATH system variable and start using xtensa-lx106-elf-gcc and other tools."
