#!/bin/bash

. common.inc.sh

check_n_args ${#} 2 "${0} <requirements_file> <location>"
REQUIREMENTS="${1}"
LOCATION="${2}"

test ! -f "${REQUIREMENTS}" && exit_error "File "${REQUIREMENTS}" not found" 1
test ! -d "${LOCATION}" && exit_error "Directory "${LOCATION}" not found" 1

. "${LOCATION}/bin/activate"
pip install -r "${REQUIREMENTS}"
