#!/bin/bash

. common.inc.sh

USAGE="${0} <python_prog> <location>"

check_n_args ${#} 2 "${USAGE}"

PYTHON="${1}"
LOCATION="$(abs_path "${2}")"

check_cmd virtualenv >/dev/null
check_cmd "${PYTHON}" >/dev/null

if [ ! -d "${LOCATION}" ]; then
  virtualenv --python="${PYTHON}" "${LOCATION}" >/dev/null 2>&1
  sed -i '4i VIRTUAL_ENV_DISABLE_PROMPT=1\n' "${LOCATION}/bin/activate"
  exit 0
else
  exit 1
fi
