#!/bin/bash

. common.inc.sh

check_n_args ${#} 2 "${0} <new_requirements_file> <location>"
REQUIREMENTS="${1}"
LOCATION="${2}"

test ! -d "${LOCATION}" && exit_error "Directory "${LOCATION}" not found" 1
test ! -f "${REQUIREMENTS}" && touch "${REQUIREMENTS}"

. "${LOCATION}/bin/activate"

FREEZE="$(pip freeze -lr "${REQUIREMENTS}")"
echo "${FREEZE}" > "${REQUIREMENTS}"
