#!/bin/bash

. common.inc.sh

check_n_args ${#} 2 "${0} <python_prog> <location>"
PYTHON="${1}"
LOCATION="${2}"

check_cmd virtualenv >/dev/null
check_cmd "${PYTHON}" >/dev/null
test -d "${LOCATION}" && exit_error "Directory "${LOCATION}" exists" 1

if [ ! -d "${LOCATION}" ]; then
  virtualenv --python="${PYTHON}" "${LOCATION}"
  sed -i '4i VIRTUAL_ENV_DISABLE_PROMPT=1\n' "${LOCATION}/bin/activate"
  . "${LOCATION}/bin/activate"
  pip install -U pip
fi
